<?php
/**
 * Created by PhpStorm.
 * User: clement
 * Date: 01/07/18
 * Time: 14:49
 */

namespace App\Utils;


class FileUtils
{
    public static function getUniqueFileName () {

        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());

    }
}